using ConnectionCustomer.Dal;
using ConnectionCustomer.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ConnectionCustomer
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }
        CustomerDal customerDal = new CustomerDal();
        int index = 0;
        List<Customer> customersList;
        private void Form1_Load(object sender, EventArgs e)
        {
            customersList = customerDal.GetAllCustomers();
            Navigate(index);
        }
        private void Navigate(int currentIndex)
        {
            if (customersList.Count > 0)
            {
                textBox1.Text = customersList[currentIndex].ID.ToString();
                textBox2.Text = customersList[currentIndex].NAME;
                textBox5.Text = customersList[currentIndex].ADDRESS;
                textBox4.Text = customersList[currentIndex].PH_NUMBER;
                textBox6.Text = customersList[currentIndex].Email;
                textBox3.Text = customersList[currentIndex].GENDER;
            }
        }

        private void addCustome_Click(object sender, EventArgs e)
        {
                Customer customer = new Customer()
                {
                    NAME = textBox2.Text,
                    ADDRESS = textBox5.Text,
                    PH_NUMBER = textBox4.Text,
                    Email = textBox6.Text,  
                    GENDER = textBox3.Text,
                };
                int result = customerDal.InsertCustomer(customer);
                if (result > 0)
                {
                textBox1.Text = String.Empty;
                textBox2.Text = String.Empty;
                textBox5.Text = String.Empty;
                textBox4.Text = String.Empty;
                textBox6.Text = String.Empty;
                textBox3.Text = String.Empty;
                textBox7.Text = "Added";
                // customersList = customerDal.GetAllCustomers();
            }
        }
        private void clear_Click(object sender, EventArgs e)
        {
            textBox1.Text = "ID will be autogenerated";
            textBox2.Text = String.Empty;
            textBox5.Text = String.Empty;
            textBox4.Text = String.Empty;
            textBox6.Text = String.Empty;
            textBox3.Text = String.Empty;
            textBox1.Focus();
        }

        private void getCustomerFirst_Click(object sender, EventArgs e)
        {
            textBox7.Text = String.Empty;
            index = 0;
            Navigate(index);
        }

        private void getCustomerPre_Click(object sender, EventArgs e)
        {
            textBox7.Text = String.Empty;
            if (index > 0)
            {
                index--;
                Navigate(index);
            }
        }

        private void getCustomerNext_Click(object sender, EventArgs e)
        {
            textBox7.Text = String.Empty;
            if (index<customersList.Count - 1)
            index ++;
            Navigate(index);
        }

        private void getCustomerLast_Click(object sender, EventArgs e)
        {
            textBox7.Text = String.Empty;
            index = customersList.Count - 1;
            Navigate(index);
        }

        private void updateCustomer_Click(object sender, EventArgs e)
        {
            textBox7.Text = String.Empty;
            Customer customer = new Customer()
            {
                ID = int.Parse(textBox1.Text),
                NAME = textBox2.Text,
                ADDRESS = textBox5.Text,
                PH_NUMBER=textBox4.Text,
                Email=textBox6.Text,
                GENDER=textBox3.Text

        };
            int result = customerDal.UpdateCustomer(customer);
            if (result > 0)
            {
                textBox1.Text = String.Empty;
                textBox2.Text = String.Empty;
                textBox5.Text = String.Empty;
                textBox4.Text = String.Empty;
                textBox6.Text = String.Empty;
                textBox3.Text = String.Empty;
                textBox7.Text = "Updated";
                textBox1.Focus();
                //customersList = customerDal.GetAllCustomers();
            }
        }

        private void deleteCustomer_Click(object sender, EventArgs e)
        {
            textBox7.Text = String.Empty;
            Customer customer = new Customer()
            {
                ID = int.Parse(textBox1.Text)
            };
            int result = customerDal.DeleteCustomer(customer);
            if (result > 0)
            {
                textBox1.Text = String.Empty;
                textBox2.Text = String.Empty;
                textBox5.Text = String.Empty;
                textBox4.Text = String.Empty;
                textBox6.Text = String.Empty;
                textBox3.Text = String.Empty;
                textBox7.Text = "Deleted";
                // customersList = customerDal.GetAllCustomers();
            }
        }
    }
}
